#ifndef SETUP_GPIO_H
#define SETUP_GPIO_H

#include "stm32f051x8.h"

/**
    #ifdef PARALLEL_TRANSMIT_SERIAL_RECEIVE
        This MC PARALLEL_TRANSMIT and SERIAL_RECEIVE while
        other MC PARALLEL_RECEIVE and SERIAL_TRANSMIT
    #endif

    #ifdef PARALLEL_RECEIVE_SERIAL_TRANSMIT
        This MC PARALLEL_RECEIVE and SERIAL_TRANSMIT while
        other MC PARALLEL_TRANSMIT and SERIAL_RECEIVE
    #endif
*/

#define PARALLEL_TRANSMIT_SERIAL_RECEIVE
#define PARALLEL_RECEIVE_SERIAL_TRANSMIT

void setup_GPIO_PINS(void);

#endif // SETUP_GPIO_H