#ifndef SETUP_GPIO_H
#define SETUP_GPIO_H

#include "stm32f051x8.h"

#define PARALLEL_TRANSMIT_SERIAL_RECEIVE
#define PARALLEL_RECEIVE_SERIAL_TRANSMIT

void setup_GPIO_PINS(void);

#endif // SETUP_GPIO_H