#include "BUTTON/button.h"
#include "FLASH/flash.h"
#include "BUFFER/buffer.h"
#include "DMA/dma.h"
#include "USART1/usart1_setup.h"
#include "GPIO/setup_GPIO.h"

uint8_t sample_1024[] = {
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
        "QWBWYHSAZIHRMDOICEOGAZLKTFRPUXNXVJTCKLPBDUNESFJYQGILDWQWGCKKTFFF"
};

volatile cbuf tx_buffer;
volatile cbuf rx_buffer;

void TEST_FLASH(void);

void setup_PERIPHERALS(void);

int main(void) {
    setup_PERIPHERALS();
    while (1);
}

void setup_PERIPHERALS(void) {
    setup_GPIO();
    setup_USART1();
    setup_DMA(tx_buffer.buffer, rx_buffer.buffer);
    setup_BUTTON();
}

/**
 * TEST FLASH
 */

void TEST_FLASH(void) {
    // change FLASH_READ_PAGE_START = FLASH_WRITE_PAGE_START for test
    circular_buf_init_reset(&tx_buffer);
    circular_buf_init_reset(&rx_buffer);
    for (int i = 0; i < BUFFER_MAX_SIZE; i++) {
        circular_buf_put(&tx_buffer, sample_1024[i]);
        circular_buf_put(&rx_buffer, 0);
    }
    write_flash_data(tx_buffer.buffer, BUFFER_MAX_SIZE);
    read_flash_data(rx_buffer.buffer, BUFFER_MAX_SIZE);
}
